# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0002_auto_20151227_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crew_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
