# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0003_crew_crew_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlpair_chief', to='brigadier.Brigadier')),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlpair_subordinate', to='brigadier.Brigadier')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
