# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0005_menulink_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='class_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
