# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0006_menulink_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
