# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0007_auto_20160123_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='locked',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='locked',
            new_name='is_locked',
        ),
        migrations.RemoveField(
            model_name='brigadier',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='balans',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='locked',
        ),
        migrations.AddField(
            model_name='brigadier',
            name='drivers_online_menu',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brigadier.Driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_state_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='is_dismissed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brigadier',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brigadier.CrewGroup'),
            preserve_default=False,
        ),
    ]
