# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0008_auto_20160128_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='code',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
