# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0009_crew_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('api_key', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='crewgroup',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadier.Service'),
        ),
    ]
