# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0011_auto_20160217_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='online',
            field=models.BooleanField(editable=False),
        ),
    ]
