# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0012_auto_20160321_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_locked',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_state_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='balance',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_dismissed',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_locked',
            field=models.BooleanField(editable=False),
        ),
    ]
