# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0014_auto_20160330_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadier.Driver'),
        ),
    ]
