# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0015_auto_20160330_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='static_priority',
            field=models.CharField(default='0', max_length=128),
            preserve_default=False,
        ),
    ]
