# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0016_crew_static_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigadier',
            name='additional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brigadier_additional_group', to='brigadier.CrewGroup'),
        ),
        migrations.AlterField(
            model_name='brigadier',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigadier_group', to='brigadier.CrewGroup'),
        ),
    ]
