# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brigadier', '0017_auto_20160520_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrigadierGroupPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='brigadier',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadier.Service'),
        ),
        migrations.AddField(
            model_name='driver',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brigadier.CrewGroup'),
        ),
        migrations.AddField(
            model_name='brigadiergrouppair',
            name='brigadier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brigadier.Brigadier'),
        ),
        migrations.AddField(
            model_name='brigadiergrouppair',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brigadier.CrewGroup'),
        ),
    ]
